## 🌱 Copyright © 2022 Nana Direct. All rights reserved
## Author: elhussein <elhussein.mohamed@nana.sa>

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: {{ include "release.name" . }}
  namespace: {{ .Release.Namespace }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "release.name" . }}

subjects:
  - kind: ServiceAccount
    name: {{ include "release.name" . }}
