## 🌱 Copyright © 2022 Nana Direct. All rights reserved
## Author: elhussein <elhussein.mohamed@nana.sa>

{{- if .Values.secret.data }}
{{- if not .Values.secret.external }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "release.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "verse.config-labels" . | indent 4 }}

type: Opaque
immutable: false
data:
{{- range $k, $v := .Values.secret.data }}
  {{ include "verse.envPrefix" $.Values }}{{ $k }}: {{ $v | b64enc }}
{{- end }}

{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: {{ include "release.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "verse.config-labels" . | indent 4 }}

spec:
  refreshInterval: {{ .Values.secret.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: {{ include "release.name" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  {{- range $k, $_ := .Values.secret.data }}
  - secretKey: {{ include "verse.envPrefix" $.Values }}{{ $k }}
    remoteRef:
      key: {{ printf "%s-%s" $.Values.secret.scope $k | trimPrefix "-" | quote }}
      version: latest
  {{- end }}
{{- end }}
{{- end }}
