## 🌱 Copyright © 2022 Nana Direct. All rights reserved
## Author: elhussein <elhussein.mohamed@nana.sa>

{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service

metadata:
  name: {{ include "release.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if eq .Values.provider "gcp" }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ include "release.name" . }}"}'
    {{- end }}

spec:
  type: {{ .Values.service.type }}
  selector: {{ include "verse.selector-labels" . | indent 4 }}
  ports:
    - name: http
      protocol: TCP
      targetPort: http-web-svc
      port: {{ .Values.service.port }}
{{- end }}

{{- if eq .Values.provider "gcp" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig

metadata:
  name: {{ include "release.name" . }}

spec:
  healthCheck:
    type: HTTP
    port: {{ .Values.service.containerPort }}
    requestPath: {{ .Values.service.healthCheck }}
{{- end }}
