name: Release Helm Charts

concurrency: release-helm

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"

jobs:
  release:
    name: Publish helm charts to Helm github pages repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm Charts Repo
        uses: actions/checkout@v3
        with:
          path: "src"
          fetch-depth: 0

      - name: Checkout Helm Charts Package
        uses: actions/checkout@v3
        with:
          ref: "pages"
          path: "dest"
          fetch-depth: 0

      - name: Install Helm
        run: curl -k https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Check helm chart templates
        run: |
          for name in src/charts/* ; do \
            if [ -d "$name" ]; then \
              helm dependency update $name/ ; \
              helm lint $name/ ; \
              echo "helm chart templates of '$name' was checked" ; \
            fi \
          done

      - name: Package Helm Charts
        shell: bash
        run: |
          for d in src/charts/*/ ; do
              echo "$d"
              helm package "$d" -u -d dest
          done

      - name: Push New Files
        shell: bash
        working-directory: dest
        run: |
          helm repo index --url https://raw.githubusercontent.com/WhatsLab/verse-helm-charts/pages/ --merge index.yaml .
          git config --global user.name "Helm Updater Bot"
          git config --global user.email "github-actions@nana.sa"
          git add --all
          git commit -m "Release helm package from ref: $GITHUB_SHA"
          git push
